logging:
    level:                
        org.springframework: ERROR
        br.com.emorgado: DEBUG
        # org.springframework.security: DEBUG

spring:
    output:
        ansi:
            enabled: ALWAYS